version: "3.5"
services:
  nginx_server:
    container_name: nginx_server
    depends_on:
      - backend
      - frontend
    build: ./nginx
    restart: always
    cap_add:
      - ALL
    volumes:
      - /nginx_data/sites/:/etc/nginx/sites-available
      - /nginx_data/letsencrypt/:/etc/letsencrypt
      - ./nginx/script/:/home
    ports:
      - 80:80
      - 443:443

  frontend:
    depends_on:
      - backend
    build: ./front
    container_name: node_front
    restart: always

  backend:
    depends_on:
      - redis_db
      - postgres_db
    build: ./back
    container_name: rust_backend
    restart: always
    environment:
      - DATABASE_URL
      - REDIS_URL
      - LOGIN
      - PASSWORD
      - JWT_SECRET_KEY
    volumes:
      - /routine_logs:/app_logs

  redis_db:
    image: redis:latest
    container_name: redis_routine
    restart: always

  postgres_db:
    image: postgres:14.5-bullseye
    container_name: postgres_routine
    restart: always
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB=portal
    cap_add:
      - ALL
    volumes:
      - /routine_data:/var/lib/postgresql/data
      - ./db:/root/db_config

